import type { Metadata } from "next";
import { Italiana } from "next/font/google";
import "./globals.css";

const italiana = Italiana({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Norishi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={italiana.className}>{children}</body>
    </html>
  );
}
